---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: hilmi-space
  labels: 
    name: regcred-hilmi-space
  annotations:
    name: regcred-hilmi-space
type: Opaque
# type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVHaHBiRzFwT21OWmFVRmthVGhHTTFwdlJtVmkiCgkJfQoJfQp9

# kubectl create secret generic regcred --from-file=.dockerconfigjson=/root/.docker/config.json