apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-deployment
  labels:
    app: expressjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expressjs
  template:
    metadata:
      labels:
        app: expressjs
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: expressjs
        image: hilmiafifi/expressjs:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
