---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: flask
          image: hilmiafifi/httpd-python:v0.1.4
          ports:
            - name: httpd
              containerPort: 8080
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
      affinity:
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - flask
              topologyKey: "kubernetes.io/hilmiafifi"
