image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_USERNAME: $DOCKERHUB_USERNAME
  DOCKER_PASSWORD: $DOCKERHUB_TOKEN
  DOCKER_IMAGE_NAME: $DOCKERHUB_USERNAME/cicd-nodejs

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:latest

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_IMAGE_NAME:latest
  only:
    - main
