apiVersion: v1
kind: Pod
metadata:
  name: expressjs-pod
  labels:
    app: expressjs
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: expressjs
    image: hilmiafifi/expressjs:latest
    ports:
    - containerPort: 8000
    env:
    - name: NODE_ENV
      value: "production"
