# xhilmi : https://s.id/hilmi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-label
  labels:
    team: finance
    version: 1.4.5
    environment: production
spec:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80