# xhilmi : https://s.id/hilmi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-node-rs
  labels:
    name: nginx-node-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-node
  template:
    metadata:
      name: nginx-node
      labels:
        app: nginx-node
    spec:
      # nodeSelector:
      #   node: master-node
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: node
          image: xhilmi/nodejs-web
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-svc
  labels:
    name: nginx-node-svc
spec:
  selector:
    app: nginx-node
  ports:
    - name: nginx
      port: 8080
      targetPort: 80
    - name: node
      port: 3030
      targetPort: 3000

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-curl
  labels:
    name: nginx-curl
spec:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    node: master-node
  containers:
    - name: nginx-curl
      image: xhilmi/nginx-curl
