# xhilmi : https://s.id/hilmi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    name: nginx-rs
spec:
  replicas: 3
  selector:
    matchExpressions: 
      - key: app
        operator: In
        values:
          - nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
        - name: storage
          emptyDir: {}
      restartPolicy: Always
      nodeSelector:
        node: master-node
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nodejs
          image: xhilmi/nodejs-writer
          volumeMounts:
            - name: storage
              mountPath: /app/html
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: storage
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          #   timeoutSeconds: 5
          #   successThreshold: 2
          #   failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    name: nginx-svc
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 30001