# xhilmi : https://s.id/hilmi
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: volume-nodejs
  labels:
    name: volume-nodejs
spec:
  replicas: 2
  selector:
    matchExpressions: 
      - key: app
        operator: In
        values:
          - nodejs
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      volumes:
        - name: nodejs
          emptyDir: {}
      restartPolicy: Always
      nodeSelector:
        node: master-node
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nodejs
          image: xhilmi/nodejs-writer
          volumeMounts:
            - name: nodejs
              mountPath: /app/html
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 5
