# xhilmi : https://s.id/hilmi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-env-configmap
data:
  APPLICATION: MY NODEJS APPS
  VERSION: 1.0.1

---
apiVersion: v1
kind: Secret
metadata:
  name: nodejs-env-secret
data:
  ENV: base64(VALUE)
stringData:
  VERSION: 1.0.1

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-env-rs
  labels:
    name: nodejs-env-rs
spec:
  replicas: 3
  selector:
    matchExpressions: 
      - key: app
        operator: In
        values:
          - nodejs-env
  template:
    metadata:
      name: nodejs-env
      labels:
        app: nodejs-env
    spec:
      volumes:
        - name: storage
          emptyDir: {}
      restartPolicy: Always
      nodeSelector:
        node: master-node
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nodejs-env
          image: xhilmi/nodejs-env
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-env-configmap
            - secretRef:
                name: nodejs-env-secret
        #   volumeMounts:
        #     - name: storage
        #       mountPath: /app/html
        # - name: nginx
        #   image: nginx:alpine
        #   volumeMounts:
        #     - name: storage
        #       mountPath: /usr/share/nginx/html
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          #   timeoutSeconds: 5
          #   successThreshold: 2
          #   failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-env-svc
  labels:
    name: nodejs-env-svc
spec:
  type: NodePort
  selector:
    name: nodejs-env
  ports:
    - port: 3030
      targetPort: 3000
      nodePort: 30001