# xhilmi : https://s.id/hilmi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-pv
  labels:
    name: nodejs-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/location

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-pvc
  labels:
    name: nodejs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
  labels:
    name: nodejs-deploy
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In 
        values:
          - nodejs
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      nodeSelector:
        node: master-node
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      restartPolicy: Always
      volumes:
        - name: nodejs-volume
          persistentVolumeClaim:
            claimName: nodejs-pvc
      containers: 
        - name: nodejs
          image: xhilmi/nodejs-writer:latest
          volumeMounts:
            - name: nodejs-volume
              mountPath: /app/html





