# xhilmi : https://s.id/hilmi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-stateful-volume
  labels:
    name: nodejs-stateful-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/location

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodejs-stateful
  labels:
    app: nodejs-stateful
spec:
  serviceName: nodejs-stateful-service
  replicas: 3
  selector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - nodejs-stateful
  volumeClaimTemplates:
    - metadata:
        name: nodejs-stateful-volume-claim
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        # dataSource:
        #   name: nodejs-pv
        #   kind: PersistentVolume
  template:
    metadata:
      name: nodejs-stateful
      labels:
        name: nodejs-stateful
    spec:
      nodeSelector:
        node: master-node
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      restartPolicy: Always
      containers: 
        - name: nodejs-stateful
          image: xhilmi/nodejs-stateful:latest
          env: 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: nodejs-stateful-volume-claim
              mountPath: /app/data

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs-svc
#   labels:
#     name: nodejs-svc
# spec:
#   ports:
#     - port: 3030
#       targetPort: 3000
#   type: ClusterIP
#   selector: 
#     name: nodejs-svc
