# xhilmi : https://s.id/hilmi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    desc: nginx-rs
  annotations:
    desc: nginx rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-rs
      - key: dept
        operator: In
        values:
          - support
          - dev
          - finance
          - sysadmin
          - noc
  template:
    metadata:
      name: nginx-rs
      labels:
        app: nginx-rs
        dept: dev
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nginx-rs
          image: nginx 
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 4