# xhilmi : https://s.id/hilmi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    desc: nginx-replica-set
  annotations:
    desc: nginx replica set
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-rs
      - key: team
        operator: In
        values:
          - finance
          - support
          - developer
          - sysadmin
          - devops
  template:
    metadata:
      name: nginx-rs
      labels:
        app: nginx-rs
        team: finance
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 3
            failureThreshold: 5

