---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
  labels:
    name: nginx-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata: 
      name: nginx
      labels:
        name: nginx
    spec:
      nodeSelector:
        node: master-node
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port
  labels:
    name: nginx-node-port
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30009