# xhilmi : https://s.id/hilmi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    name: nginx-svc
spec:
  selector: 
    name: nginx
  ports:
    - port: 8080
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    name: curl-pod
spec:
  containers:
    - name: curl-pod
      image: xhilmi/curl-pod



  