# xhilmi : https://s.id/hilmi
---
apiVersion: v1
kind: Service
metadata:
  name: domain-svc
  labels: 
    desc: domain-svc
  annotations:
    desc: domain-svc
spec: 
  type: ExternalName
  externalName: example.com
  ports:
    - port: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-curl
  labels:
    name: nginx-curl
  annotations:
    name: nginx-curl
spec:
  nodeSelector:
    node: master-node
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  containers:
    - name: nginx-curl
      image: xhilmi/nginx-curl
      # ports: 
      #   - containerPort: 80