apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: nginx
          image: hilmiafifi/nginx:latest
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
#      imagePullSecrets:
#        - name: hilmiafifi
#      restartPolicy: Always
#  namespace: nginx-kubernetes-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
